# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_auto_20180119_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=80),
        ),
    ]
